--LEFT, RIGHT,LEN
SELECT LEFT('EMEL DURHANOÐLU DOÐAN',4)
SELECT RIGHT('EMEL DURHANOÐLU DOÐAN',4)
SELECT LEN('EMEL DURHANOÐLU DOÐAN')
SELECT LEFT('EMEL DURHANOÐLU DOÐAN',CHARINDEX(' ','EMEL DURHANOÐLU DOÐAN'))
SELECT RIGHT('EMEL DURHANOÐLU DOÐAN',LEN('EMEL DURHANOÐLU DOÐAN')-CHARINDEX(' ','EMEL DURHANOÐLU DOÐAN'))

SELECT LEFT(NAMESURNAME,CHARINDEX(' ',NAMESURNAME)),
RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME))
FROM USERS