-- ORTALAMA TESLÝMAT SÜRESÝ HESAPLATMA
SELECT
C.CITY,
--DATEPART(YEAR,O.DATE_)AS AY,
--DATEPART(MONTH,O.DATE_)AS AY,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMATESLIMATSURESI,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MAKS,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MINS,
SUM(O.TOTALPRICE) AS TOPLAMTUTAR,
COUNT(O.ID) AS SIPARISSAYISI

FROM
ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
--INNER JOIN ITEMS IT ON IT.ID= OD.ITEMID



GROUP BY C.CITY

ORDER BY 1,2 