--SUBSTRING
SELECT* FROM USERS WHERE USERNAME_ LIKE 'O%'
SELECT* FROM USERS WHERE USERNAME_ LIKE '%O'
SELECT* FROM USERS WHERE SUBSTRING (USERNAME_,1,1)='O'
-- SONU O ÝLE BÝTEN KULLANACAÐIZ

SELECT* FROM USERS WHERE SUBSTRING (USERNAME_,LEN(USERNAME_),1)='O'