-- ÜRÜN FÝYAT ANALÝZÝ ÝÇ ÝÇE SELECT
SET STATISTICS IO ON 
SELECT 
ITM.ITEMCODE,
ITM.ITEMNAME,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTFIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS SIPARISSAY
FROM ITEMS ITM

ORDER BY ITM.ITEMNAME