SELECT * FROM CUSTOMERS

WHERE CITY IN ('ÝSTANBUL', 'ANKARA', 'ÝZMÝR')

UPDATE CUSTOMERS SET GENDER='ERKEK' WHERE GENDER='E'
UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'

DELETE FROM CUSTOMERS WHERE ID=18