SELECT U. ID, U.USERNAME_, A.ADRESSTEXT
FROM USERS U
--JOIN ADRESS A ON A. USERID= U.ID
--LEFT JOIN ADRESS A ON A.USERID=U.ID
--RIGHT JOIN ADRESS A ON A.USERID=U.ID
--INNER JOIN ADRESS A ON A.USERID=U.ID
FULL JOIN ADRESS A ON A.USERID=U.ID