--SELECT COUNT(*) FROM SALES

--SELECT MAX(AMOUNT),MIN(AMOUNT),COUNT(*), SUM(AMOUNT), AVG(AMOUNT) FROM SALES

--SELECT AVG(AMOUNT) FROM SALES

--SELECT MAX(TOTALPRICE),MIN(TOTALPRICE),COUNT(TOTALPRICE), SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES
SELECT MAX(TOTALPRICE),MIN(TOTALPRICE),COUNT(TOTALPRICE), SUM(TOTALPRICE), AVG(TOTALPRICE) FROM SALES WHERE CITY='ÝSTANBUL'