--Kullanýcý adý	
--adsoyad	il	ilçe	semt 	açýk adres	
--sipariþýd	tarih	toplamtutar	
--ödeme tarihi	banka onay	fatura tarihi	
--kargo fiþ


SELECT
U.USERNAME_,U. NAMESURNAME, C.CITY, T.TOWN,D.DISTRICT,
A.ADDRESSTEXT, O.ID, O.DATE_, O.TOTALPRICE, P.PAYMENTTOTAL
, P.APPROVECODE, I.DATE_, I.CARGOFICHENO, IT.ITEMCODE
, IT.ITEMNAME, OD.UNITPRICE, OD.AMOUNT, OD.LINETOTAL
FROM

ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID= OD.ITEMID

--WHERE O.ID= 2389
 WHERE U.USERNAME_='S_BVYVKCENGIZ'

--ORDER BY U.USERNAME_
