--LOWER UPPER REVERSE REPLICATE
SELECT LOWER('EMEL')
SELECT UPPER('eMeL')
SELECT REVERSE('EMEL')
SELECT REPLICATE('0',10) --STANDART KARAKTER SAYISINI TUTTURMAK ÝÇÝN
--SELECT CONCAT(REPLICATE('0',7-LEN(ID)),ID) AS A FROM USERS U-- USERID ÝÇÝNDEKÝ TÜM ÝDLERÝ 7 KARAKTER YAPTIK ÖNÜNE SIFIR EKLEYEREK
SELECT REPLICATE('0',7-LEN(ID))+CONVERT(VARCHAR,ID) FROM USERS U-- USERID ÝÇÝNDEKÝ TÜM ÝDLERÝ 7 KARAKTER YAPTIK ÖNÜNE SIFIR EKLEYEREK
