SELECT TOP 10
CITY,SUM(TOTALPRICE)
--MIN(TOTALPRICE) AS MINPRICE, MAX(TOTALPRICE) AS MAXPRICE, 
--COUNT(FICHENO) AS ROWCOUNT_,
--AVG(TOTALPRICE) ORTALAMA
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC
