-- ÞEHÝRLERE GÖRE SÝPARÝÞ MÝKTARLARI
--ÞEHÝR ADI, TOPLAM SÝPARÝÞ TUTARI, TOPLAM SÝPARÝÞ ADEDÝ
--TOPLAM SÝPARÝÞ SAYISI
SELECT
C.CITY, SUM (OD.LINETOTAL) TOPLAMTUTAR, 
SUM( OD.AMOUNT) TOPLAMADET, 
COUNT(OD.ID) SIPARISSAYISI

FROM

ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID= OD.ITEMID

GROUP BY C.CITY
--ORDER BY C.CITY
--ORDER BY SUM(OD.LINETOTAL) DESC
ORDER BY 2 DESC --2. SÜTUNA GÖRE AZALAN SIRALAR.