SELECT
DATEPART(YEAR,O.DATE_) YIL,
DATEPART(MONTH,O.DATE_) AY,
CASE
WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ÞUBAT'
END AS AYADI,


SUM(OD.LINETOTAL) TOPLAMTUTAR,
SUM(OD.AMOUNT) TOPLAMADET,
COUNT(OD.ID) SIPARISADEDI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) ORTALAMABIRIMFIYAT
FROM

ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID= OD.ITEMID

GROUP BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
--ORDER BY 1,2

ORDER BY 2,1