SELECT
IT.CATEGORY1, IT.CATEGORY2,--IT.CATEGORY3,IT.CATEGORY4,
SUM(OD.LINETOTAL) TOPLAMTUTAR,
SUM(OD.AMOUNT) TOPLAMADET,
COUNT(OD.ID) SIPARISADEDI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) ORTALAMABIRIMFIYAT
FROM

ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
INNER JOIN ITEMS IT ON IT.ID= OD.ITEMID

GROUP BY IT.CATEGORY1, IT.CATEGORY2--,IT.CATEGORY3,IT.CATEGORY4
ORDER BY 1,2,3,4 ASC
