-- ORTALAMA TESLÝMAT SÜRESÝ HESAPLATMA
SELECT
--O.ID AS SIPARISID,
--O.DATE_ AS SIPARISTARIHI,
--I.DATE_ AS FATURATARIHI,
--DATEDIFF(HOUR, O.DATE_, I.DATE_) AS ORT_TESLIMATSURESAAT
AVG(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS ORT_TESLIMATSURESAAT,
MIN(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS MIN_TESLIMATSURESAAT,
MAX(DATEDIFF(HOUR, O.DATE_, I.DATE_)) AS MAX_TESLIMATSURESAAT


FROM
ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON O.ID=OD.ORDERID
--INNER JOIN ITEMS IT ON IT.ID= OD.ITEMID

