SELECT * FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'
--ORDER BY ID DESC
--ORDER BY CUSTOMERNAME
--ORDER BY CUSTOMERNAME DESC

--ORDER BY BIRTHDATE DESC

--ORDER BY CITY, CUSTOMERNAME
--ORDER BY CITY, CUSTOMERNAME DESC
--ORDER BY CITY, DISTRICT,CUSTOMERNAME

ORDER BY 3, 2




