SELECT U.NAMESURNAME AS ADSOYAD, U.EMAIL MAILADRESI,
U.GENDER CINSIYET,A.ADRESSTEXT AS ACIKADRES,
C.COUNTRY AS ULKE, CT.CITY AS SEHIR, T.TOWN AS ILCE, D.DISTRICT AS SEMT
FROM USERS U, ADRESS A,COUNTRIES C, CITIES CT, TOWNS T, DISTRICTS D
WHERE U.ID=A.USERID AND C.ID= A.COUNTRYID AND 
CT.ID=A.CITYID AND T.ID=A.TOWNID AND D.ID= A.DISTRICTID
AND USERID=4