SELECT DATEPART(YEAR,DATE_) AS YIL,
DATEPART(MONTH,DATE_) AS AY,
PAYMENTTYPE AS ODEMETURU,
CASE 
WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
WHEN PAYMENTTYPE=2 THEN 'HAVALE'
END AS ACIKLAMA,
SUM(PAYMENTTOTAL) AS TUTAR

FROM PAYMENTS

GROUP BY PAYMENTTYPE,DATEPART(MONTH,DATE_),DATEPART(YEAR,DATE_)
ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_), PAYMENTTYPE
