CREATE TABLE Users(
ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDDATE DATETIME,
TELNO1 VARCHAR(15),
TELNO2 VARCHAR(15)
CONSTRAINT PK_USERS  PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE ITEMS(
ID INT IDENTITY(1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50)
CONSTRAINT PK_ITEMS  PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE ORDERS(
ID INT IDENTITY(1,1),
USERID INT,
DATE_ DATETÝME,
TOTALPRICE FLOAT,
STATUS TINYINT,
CONSTRAINT PK_ORDERS  PRIMARY KEY CLUSTERED(ID ASC))
CREATE TABLE ORDERDETAILS(
ID INT IDENTITY(1,1),
ORDERID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT
CONSTRAINT PK_ORDERDETAILS  PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE PAYMENTS(
ID INT IDENTITY(1,1),
ORDERID INT,
PAYMENTTYPE TINYINT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(100),
PAYMENTTOTAL FLOAT
CONSTRAINT PK_PAYMETS  PRIMARY KEY CLUSTERED(ID ASC))
CREATE TABLE INVOICE(
ID INT IDENTITY(1,1),
ORDERID INT,
DATE_ DATETIME,
ADRESSID INT,
CARGOFICHENO VARCHAR(20),
TOTALPRICE FLOAT
CONSTRAINT PK_INVOICE  PRIMARY KEY CLUSTERED(ID ASC))
CREATE TABLE INVOICEDETAILS(
ID INT IDENTITY(1,1),
INVOICEID INT,
ORDERDETAILID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT,
CONSTRAINT PK_INVOICEDETAILS  PRIMARY KEY CLUSTERED(ID ASC))
CREATE TABLE ADRESS(
ID INT IDENTITY(1,1),
COUNTRYID TINYINT,
CITYID SMALLINT,
TOWNID INT,
DISTRICTID INT,
POSTALCODE VARCHAR(10),
ADRESSTEXT VARCHAR(500),
USERID INT
CONSTRAINT PK_ADRESS  PRIMARY KEY CLUSTERED(ID ASC))
CREATE TABLE COUNTRIES(
ID TINYINT IDENTITY(1,1),
COUNTRY VARCHAR(50)
CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE CITIES(
ID SMALLINT IDENTITY(1,1),
COUNTRYID TINYINT,
CITY VARCHAR(50)
CONSTRAINT PK_CITIES  PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE TOWNS(
ID INT IDENTITY(1,1),
CITYID SMALLINT,
TOWN VARCHAR(50)
CONSTRAINT PK_TOWNS  PRIMARY KEY CLUSTERED(ID ASC))

CREATE TABLE DISTRICTS(
ID INT IDENTITY(1,1),
TOWNID INT,
DISTRICT VARCHAR(50)
CONSTRAINT PK_DISTRICTS  PRIMARY KEY CLUSTERED(ID ASC))
